alias chrome-canary="open -a /Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary --args --disable-web-security"
alias build="bash ~/code/frontend/scripts/build-default.sh"
alias build-min="bash ~/code/frontend/scripts/build-min.sh"
alias test="bash ~/code/frontend/scripts/test-all.sh"
alias replicante0="sudo ssh -i [cert-file] ubuntu@[ip]"
alias replicante2="sudo ssh -i [cert-file] ubuntu@[ip]"
alias replicante3="sudo ssh -i [cert-file] ubuntu@[ip]"
alias tracker-airfit="sudo ssh -i [cert-file] ubuntu@[ip]"
